export const SCENE_KEYS = {
  PRELOAD: 'PRELOAD',
  INTRO: 'INTRO',
  DOG_CHOICE: 'DOG_CHOICE',
  LEVEL_CHOICE: 'LEVEL_CHOICE',
  MAP: 'MAP',
  COACH: 'COACH',
  CORRECTION: 'CORRECTION',
  SOLUTION: 'SOLUTION',
};
