export const SCENE_KEYS = {
  PRELOAD: 'PRELOAD',
  INTRO: 'INTRO',
  LEVEL_CHOICE: 'LEVEL_CHOICE',
  MAP: 'MAP',
  COACH: 'COACH',
  CORRECTION: 'CORRECTION',
  SOLUTION: 'SOLUTION',
  END: 'END',
};
