export const LGDT_COLORS = {
  BROWN: '#b8853f', BROWNNUM: 0xb8853f,
  GREEN: '#5b6639', GREENNUM: 0x5b6639,
  ORANGE: '#fb9339', ORANGENUM: 0xfb9339,
  CYAN: '#08d9b5', CYANNUM: 0x08d9b5,
  YELLOW: '#fbc739', YELLOWNUM: 0xfbc739,
  BLUE: '#089ad9', BLUENUM: 0x089ad9,
};

export const STYLECONFIG = {
  // MAIN.js
  WIDTH: 800,
  HEIGHT: 600,
  MAIN_BACKGROUND_COLOR: '#2d5016', // Dark GREEN

  // INTROSCENE.js
  INTRO_BACKGROUND_COLOR: '#1a1a2e', // Darker Gray
  INTRO_SCENE_TITLE_FONT_SIZE: '42px',
  INTRO_SCENE_TITLE_FONT_FAMILY: 'PLAY, Arial',
  INTRO_SCENE_TITLE_COLOR: '#ffffff', // White
  INTRO_SCENE_TITLE_FONT_STYLE: 'bold',

  // RULES TEXT
  RULES_FONT_SIZE: '15px',
  RULES_FONT_FAMILY: 'PLAY, Arial',
  RULES_COLOR: '#e0e0e0', // Light gray

  // START BUTTON
  START_BUTTON_FONT_SIZE: '22px',
  START_BUTTON_FONT_FAMILY: 'PLAY, Arial',
  START_BUTTON_FONT_COLOR: '#ffffff', // White
  START_BUTTON_FONT_STYLE: 'bold',
  START_BUTTON_COLOR: LGDT_COLORS.BLUENUM,
  START_BUTTON_HOVER_COLOR: LGDT_COLORS.ORANGENUM,
  
  // HIDE BUTTON
  HIDE_BUTTON_FONT_SIZE: '22px',
  HIDE_BUTTON_FONT_FAMILY: 'PLAY, Arial',
  HIDE_BUTTON_FONT_COLOR: '#ffffff', // White
  HIDE_BUTTON_FONT_STYLE: 'bold',
  HIDE_BUTTON_COLOR: LGDT_COLORS.ORANGE,
  HIDE_BUTTON_HOVER_COLOR: LGDT_COLORS.YELLOWNUM,

  // SELECTLEVELSCENE.js
  SELECT_LEVEL_BACKGROUND_COLOR: 0xffffff,

  // Page TITLE
  SELECT_LEVEL_TITLE_FONT_SIZE: '36px',
  SELECT_LEVEL_TITLE_FONT_FAMILY: 'Lilita One, Arial',
  SELECT_LEVEL_TITLE_COLOR: LGDT_COLORS.YELLOW,
  SELECT_LEVEL_TITLE_FONT_STYLE: 'bold',

  // CARD BACKGROUNDs & BORDERs
  CARD_BACKGROUND_UNLOCKED: LGDT_COLORS.BROWNNUM,
  CARD_BACKGROUND_LOCKED: 0x202020, // Dark BROWN
  CARD_BORDER_UNLOCKED: LGDT_COLORS.BROWNNUM,
  CARD_BORDER_LOCKED: 0x3a3a3a, // Light BROWN fading on gray

  // LEVEL NUMber BADGE
  CARD_BADGE_COLOR_UNLOCKED: LGDT_COLORS.GREENNUM,
  CARD_BADGE_COLOR_LOCKED: 0x404040, // Lighter BROWN fading on gray
  CARD_BADGE_FONT_SIZE: '22px',
  CARD_BADGE_FONT_FAMILY: '"Lobster Two", cursive',

  // CARD TITLE
  CARD_TITLE_FONT_SIZE: '16px',
  CARD_TITLE_FONT_FAMILY: '"PLAY", sans-serif',
  CARD_TITLE_COLOR_UNLOCKED: '#ffffff', // White
  CARD_TITLE_COLOR_LOCKED: '#555555', // Darker than gray

  // CARD DESCRIPTION
  CARD_DESCRIPTION_FONT_SIZE: '13px',
  CARD_DESCRIPTION_FONT_FAMILY: '"PLAY", sans-serif',
  CARD_DESCRIPTION_COLOR_UNLOCKED: '#ffffff', // White
  CARD_DESCRIPTION_COLOR_LOCKED: '#484848', // Dark gray

  // PLAY BUTTON
  CARD_PLAY_BUTTON_FONT_SIZE: '15px',
  CARD_PLAY_BUTTON_FONT_FAMILY: '"Lilita One", sans-serif',
  CARD_PLAY_BUTTON_FONT_COLOR: LGDT_COLORS.GREEN,
  CARD_PLAY_BUTTON_COLOR: LGDT_COLORS.ORANGENUM,
  CARD_PLAY_BUTTON_HOVER_COLOR: LGDT_COLORS.ORANGENUM,

  // LOCK ICON & RESET link
  CARD_LOCK_FONT_SIZE: '28px',
  RESET_TEXT_FONT_SIZE: '14px',
  RESET_TEXT_FONT_FAMILY: 'Inter, Arial',
  RESET_TEXT_COLOR: '#666666', // Gray
  RESET_TEXT_HOVER_COLOR: '#aaaaaa', // Lighter gray

  // SELECTTREATSCENE.js
  SELECT_TREAT_SUBTITLE_COLOR: '#888888',
  SELECT_TREAT_BADGE_COLOR_CROQUETTES: LGDT_COLORS.GREENNUM,
  SELECT_TREAT_BADGE_COLOR_SECHE: LGDT_COLORS.GREENNUM,
  SELECT_TREAT_BADGE_COLOR_HUMIDE: LGDT_COLORS.GREENNUM,
  SELECT_TREAT_BADGE_NAME_COLOR: LGDT_COLORS.YELLOW,
  SELECT_TREAT_BADGE_NAME_FONT_SIZE: '13px',
  SELECT_TREAT_IMAGE_SIZE: 36,

  // GAMESCENE
  GAME_SCENE_GROUND_COLOR: 0x8B6914, // BROWN
  GAME_SCENE_HERB_COLOR: 0x2d9916, // GREEN

  // GAUGE LABELS
  GAUGE_LABEL_FONT_SIZE: '13px',
  GAUGE_LABEL_FONT_FAMILY: 'PLAY, Arial',
  GAUGE_LABEL_CONSENT_COLOR: '#aaffaa', // Light lime
  GAUGE_LABEL_AGITATION_COLOR: '#ffcc88', // Lighter ORANGE

  // CONSENT GAUGE — 10 SEGMENTs, index 0 = VERY low, index 9 = max
  SEGMENT_CONSENT_GAUGE_COLORS: [
    0xee4033, 0xee4033,
    0xff7010, 0xff9910,
    0xffcc00, 0xaadd00,
    0x66cc33, 0x22cc70,
    0x22cc70, 0x22cc70,
  ],
  SEGMENT_CONSENT_GAUGE_CURSOR_COLOR: 0xffffff,
  SEGMENT_CONSENT_GAUGE_LABEL_FONT_SIZE: '14px',
  SEGMENT_CONSENT_GAUGE_LABEL_FONT_STYLE: 'bold',
  SEGMENT_CONSENT_GAUGE_LABEL_COLOR: '#ffffff',

  // CONSENT BAR layout
  GAUGE_CONSENT_BAR_WIDTH: 400,
  GAUGE_CONSENT_BAR_HEIGHT: 20,
  GAUGE_CONSENT_BAR_TOP_Y: 48,
  GAUGE_CONSENT_BAR_BORDER_COLOR: 0x333333,
  GAUGE_CONSENT_CURSOR_WIDTH: 4,
  GAUGE_CONSENT_CURSOR_HEIGHT_OVERFLOW: 8,

  // AGITATION GAUGE — 10 SEGMENTs, index 0 = calm, index 9 = max stREss
  GAUGE_AGITATION_SEGMENT_COUNT: 10,
  GAUGE_AGITATION_SEGMENT_WIDTH: 20,
  GAUGE_AGITATION_SEGMENT_HEIGHT: 14,
  GAUGE_AGITATION_SEGMENT_GAP: 4,
  GAUGE_AGITATION_SEGMENT_COLORS: [
    0x22cc70, 0x22cc70,
    0x88dd00, 0xaadd00,
    0xffcc00, 0xffcc00,
    0xff9910, 0xff7010,
    0xee4033, 0xee4033,
  ],
  GAUGE_AGITATION_LABEL_FONT_SIZE: '11px',
  GAUGE_AGITATION_LABEL_COLOR: '#cc5500',
  GAUGE_AGITATION_VERTICAL_OFFSET: 54,

  // CONSENT state LABELS keyed by CONSENT integer value (-5 to +5)
  CONSENT_LABELS: {
    '-5': 'Très stressé',
    '-4': 'Stressé',
    '-3': 'Stressé',
    '-2': "Mal à l'aise",
    '-1': 'Réticent',
    '0': 'Neutre',
    '1': "À l'aise",
    '2': 'Confiant',
    '3': 'Confiant',
    '4': 'Content',
    '5': 'Très content !',
  },

  // STEP HUD
  STEP_HUD_FONT_SIZE: '16px',
  STEP_HUD_FONT_FAMILY: 'PLAY, Arial',
  STEP_HUD_COLOR: '#ffffff', // White
  STEP_HUD_BACKGROUND_COLOR: '#000000', // Black

  // HELP BUTTON & instructions PANEL
  HELP_BUTTON_FONT_SIZE: '16px',
  HELP_BUTTON_COLOR: '#ffffff',
  HELP_BUTTON_BACKGROUND_COLOR: '#334455',
  HELP_PANEL_BACKGROUND_COLOR: 0x111133,
  HELP_PANEL_BACKGROUND_ALPHA: 0.94,
  HELP_PANEL_TITLE_FONT_SIZE: '17px',
  HELP_PANEL_TITLE_COLOR: '#ffffff',
  HELP_PANEL_TEXT_FONT_SIZE: '14px',
  HELP_PANEL_TEXT_COLOR: '#cccccc',
  HELP_PANEL_ACTIVE_STEP_COLOR: '#ffee44',
  HELP_PANEL_CROSS_COLOR: '#aaaaaa',

  // DOG PROFILE disPLAY
  DOG_PROFILE_FONT_SIZE: '16px',
  DOG_PROFILE_FONT_FAMILY: 'Inter, Arial',
  DOG_PROFILE_COLOR: '#ffffffaa', // Semi-transpaREnt white

  // BAR HUD
  BAR_BACKGROUND_COLOR: 0x333333, // Gray
  BAR_TEXT_FONT_SIZE: '14px',
  BAR_TEXT_FONT_FAMILY: 'PLAY, Arial',
  BAR_TEXT_COLOR: '#ffffff', // White
  CONSENT_BAR_START_COLOR: LGDT_COLORS.GREENNUM,
  AGITATION_BAR_START_COLOR: LGDT_COLORS.ORANGENUM,
  ICON_FONT_SIZE: '20px',
  ICON_FONT_FAMILY: '"FONT Awesome 6 FREe"',
  ICON_FONT_STYLE: '900',
  ICON_COLOR: '#ffffff', // White

  // SPEECH BUBBLE
  SPEECH_BUBBLE_FONT_SIZE: '18px',
  SPEECH_BUBBLE_FONT_FAMILY: 'PLAY, Arial',
  SPEECH_BUBBLE_COLOR: '#ffffff',
  SPEECH_BUBBLE_BACKGROUND_COLOR: '#1a1a1a',

  // ACTION SPEECH (persistent callout for "on attache / on détache")
  ACTION_SPEECH_FONT_SIZE: '16px',
  ACTION_SPEECH_FONT_FAMILY: 'PLAY, Arial',
  ACTION_SPEECH_COLOR: '#ffffff',
  ACTION_SPEECH_BACKGROUND_COLOR: '#1a1a1a',

  // ENDSCENE.js
  // RETRY BUTTON
  RETRY_BUTTON_FONT_SIZE: '22px',
  RETRY_BUTTON_FONT_FAMILY: 'PLAY, Arial',
  RETRY_BUTTON_FONT_COLOR: '#1a1a2e', // Darker Gray
  RETRY_BUTTON_FONT_STYLE: 'bold',
  RETRY_BUTTON_COLOR: LGDT_COLORS.YELLOWNUM,
  RETRY_BUTTON_HOVER_COLOR: LGDT_COLORS.ORANGENUM,
  BACKGROUND_COLOR: '#1a1a2e', // Darker Gray

  END_SCENE_TITLE_FONT_SIZE: '30px',
  END_SCENE_TITLE_FONT_FAMILY: 'Lilita One, Arial',
  END_SCENE_TITLE_COLOR: '#ffffff', // White

  // FINAL CONSENT/AGITATION disPLAY
  FINAL_CONSENT_FONT_SIZE: '20px',
  FINAL_CONSENT_FONT_FAMILY: 'PLAY, Arial',
  FINAL_CONSENT_COLOR: '#aaffaa', // Light lime

  FINAL_AGITATION_FONT_SIZE: '20px',
  FINAL_AGITATION_FONT_FAMILY: 'PLAY, Arial',
  FINAL_AGITATION_COLOR: '#ffcc88', // Lighter ORANGE

  // FINAL MESSAGE
  MAIN_MESSAGE_FONT_SIZE: '20px',
  MAIN_MESSAGE_FONT_FAMILY: 'Inter, Arial',
  MAIN_MESSAGE_COLORS: {
    VERYNEGATIVE: '#ff4444', // REd fading on ORANGE
    NEGATIVE: '#ff9944', // Light ORANGE
    NEUTRAL: LGDT_COLORS.YELLOW,
    POSITIVE: '#44cc44', // Light GREEN
  },

  // UNLOCK BADGE
  UNLOCK_BADGE_FONT_SIZE: '18px',
  UNLOCK_BADGE_FONT_FAMILY: 'PLAY, Arial',
  UNLOCK_BADGE_COLOR: LGDT_COLORS.CYAN,

  // MENU BUTTON
  MENU_BUTTON_BACKGROUND: 0x334455, // Light dark BLUE
  MENU_BUTTON_HOVER: 0x4a6a88, // Lighter dark BLUE
  MENU_BUTTON_FONT_COLOR: '#ffffff', // White

  END_SCENE_STATUS_FONT_SIZE: '18px',
  END_SCENE_STATUS_FONT_FAMILY: 'PLAY, Arial',
  END_SCENE_STATUS_COLOR: '#ffffff', // White

  END_SCENE_HINT_FONT_SIZE: '14px',
  END_SCENE_HINT_FONT_FAMILY: 'Inter, Arial',
  END_SCENE_HINT_COLOR: LGDT_COLORS.YELLOW,

  END_SCENE_SUCCESS_COLOR: LGDT_COLORS.CYAN,
  END_SCENE_FAIL_COLOR: '#ff6644', // ORANGE
  END_SCENE_RESULT_FONT_SIZE: '24px',
  END_SCENE_RESULT_FONT_FAMILY: 'Lobster Two, Arial',

  // GAMESCENElvl4.js — STREET SCENE
  LEVEL4_STREET_SIDEWALK_COLOR: 0x8a8a8a,
  LEVEL4_STREET_ROAD_COLOR: 0x505050,
  LEVEL4_DISTRACTION_EMOTE_FONT_SIZE: '24px',
  LEVEL4_GAME_OVER_OVERLAY_COLOR: 0x000000,
  LEVEL4_GAME_OVER_OVERLAY_ALPHA: 0.72,
  LEVEL4_GAME_OVER_TITLE_FONT_SIZE: '26px',
  LEVEL4_GAME_OVER_TITLE_COLOR: '#ff5544',
  LEVEL4_GAME_OVER_MESSAGE_FONT_SIZE: '15px',
  LEVEL4_GAME_OVER_MESSAGE_COLOR: '#ffffff',
  LEVEL4_HUMAN_SOCIABLE_COLOR: 0xcc44cc,
  LEVEL4_HUMAN_SCARED_COLOR: 0xff6622,
  LEVEL4_DOG_SOCIABLE_COLOR: 0x4466cc,
  LEVEL4_DOG_REACTIVE_COLOR: 0xcc2222,
};
